name    'herculesteam-augeasproviders_nagios'
version '1.0.0'
source 'git://github.com/hercules-team/augeasproviders_nagios'
author 'Dominic Cleal, Raphael Pinson'
license 'Apache 2.0'
summary 'Augeas-based nagios types and providers for Puppet'
description 'This module provides types/providers for nagios using the Augeas configuration API library.'
project_page 'http://augeasproviders.com'
